### ISSUE TITLE
How make separate file for each language ?

### ISSUE THREAD

**Issue by atach** [testmonitor/laravel-vue-i18n-generator#4]
Thanks for the package. Can you tell me how to implement a separate file for each language?

**Comment by Frankisgek** [comment]
Thank you for your appreciation of the package! The primary purpose of this package is to combine all translations into a single translation file for use in Vue i18n. Unfortunately, it does not support creating separate files for each language, as that would go against the intended functionality of the package.

If you need separate files for each language, you might need to consider an alternative approach or modify the package to fit your specific requirements.
