### ISSUE TITLE
Translation json do not includes translations from subfolders 

### ISSUE THREAD

**Issue by anagylynx** [testmonitor/laravel-vue-i18n-generator#5]
Hello, I have subfolders in my translations folder that are ignored when I generate the json, can you please provide support for subfolders? Thank you! 

![image](https://github.com/testmonitor/laravel-vue-i18n-generator/assets/47772992/971c2e70-d6e8-44c1-b7a1-3a1efb69cf54)

**Comment by Frankisgek** [comment]
Hi @anagylynx,

Thank you for your feedback. We're currently focused on other priorities and don't have time to address this right now. However, if you'd like to contribute, we’d be happy to review a pull request that adds this feature.

Thanks for your understanding!
